export const SET_LOADING = "SET_LOADING"

export const GET_COURSES = "GET_COURSES"
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS"

export const GET_COURSES_BY_CATEGORY = "GET_COURSES_BY_CATEGORY"
export const GET_COURSES_BY_CATEGORY_SUCCESS = "GET_COURSES_BY_CATEGORY_SUCCESS"