// export const USER_LOGGED_IN = "USER_LOGGED_IN";
// export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
// export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
// export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
// export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
// export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

const ACTION = {
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FALURE',
    USER_LOG_IN: 'USER_LOG_IN',
    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    USER_LOG_OUT: 'USER_LOG_OUT',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
};
export default ACTION;