
const ACTION = {
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FALURE',
    USER_LOG_IN: 'USER_LOG_IN',
    USER_LOG_OUT: 'USER_LOG_OUT',
    CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
    GET_COURSE: "GET_COURSE",
    GET_COURSE_REQUESTED: "GET_COURSE_REQUESTED"
};
export default ACTION;
